### ISSUE TITLE
Fix Sequelize Catch Statements always returning error 500

### ISSUE THREAD

**Issue by SpellBreakerZA** [301-Redirection/DBC#191]

**Comment by vector67** [comment]
Please give a more descriptive comment. Explain in what situation this occurs, and why it's a problem for the user.

**Comment by SpellBreakerZA** [comment]
Sequelize will always throw an error in a catch statement even if the operation succeeds. Hence the server returns a 500 error on the saving despite the save is successful...

**Comment by vector67** [comment]
This doesn't seem to be the case anymore, please confirm. @SpellBreakerZA
