### ISSUE TITLE
Redundancy in database and front-end breaking...

### ISSUE THREAD

**Issue by SpellBreakerZA** [301-Redirection/DBC#193]
* sigh *

**Comment by vector67** [comment]
Please give a more descriptive issue message.

**Comment by SpellBreakerZA** [comment]
The front-end sends the whole ability and item object instead of the only required values. Example object sent:
`"heroes":[  
      {  
         "name":"bristleback",
         "abilities":[  
            {  
               "name":"Warpath",
               "type":"R",
               "src":"http://localhost:3000/static/abilities/images/bristleback_r.png",
               "priority":0,
               "index":3
            },
            {  
               "name":"Talents",
               "type":"T",
               "src":"https://image.winudf.com/v2/image/Y29tLnRyZW5jaHdhcmZhcmVkb3RhLnRhbGVudHRyZWVmb3Jkb3RhX2ljb25fNTgyZ2hqbzg/icon.png?w=170&fakeurl=1&type=.png",
               "priority":1,
               "index":4
            },
            {  
               "name":"Viscous Nasal Goo",
               "type":"Q",
               "src":"http://localhost:3000/static/abilities/images/bristleback_q.png",
               "priority":2,
               "index":0
            },
            {  
               "name":"Quill Spray",
               "type":"W",
               "src":"http://localhost:3000/static/abilities/images/bristleback_w.png",
               "priority":3,
               "index":1
            },
            {  
               "name":"Bristleback",
               "type":"E",
               "src":"http://localhost:3000/static/abilities/images/bristleback_e.png",
               "priority":4,
               "index":2
            }
         ],
         "abilityLevels":"qwqwqrqwwtereetenrntnnnnt",
         "items":[  
            {  
               "id":3,
               "name":"broadsword",
               "cost":1200,
               "components":"null",
               "niceName":"Broadsword",
               "type":0,
               "createdAt":"2018-08-25T19:25:39.000Z",
               "updatedAt":"2018-08-25T19:25:39.000Z",
               "url":"http://localhost:3000/static/items/images/3.png"
            },
            {  
               "id":50,
               "name":"phase_boots",
               "cost":1360,
               "components":[  
                  {  
                     "id":2,
                     "name":"blades_of_attack",
                     "cost":430,
                     "components":"null",
                     "niceName":"Blades of Attack",
                     "type":0,
                     "createdAt":"2018-08-25T19:25:39.000Z",
                     "updatedAt":"2018-08-25T19:25:39.000Z",
                     "url":"http://localhost:3000/static/items/images/2.png"
                  },
                  {  
                     "id":2,
                     "name":"blades_of_attack",
                     "cost":430,
                     "components":"null",
                     "niceName":"Blades of Attack",
                     "type":0,
                     "createdAt":"2018-08-25T19:25:39.000Z",
                     "updatedAt":"2018-08-25T19:25:39.000Z",
                     "url":"http://localhost:3000/static/items/images/2.png"
                  },
                  {  
                     "id":29,
                     "name":"boots",
                     "cost":500,
                     "components":"null",
                     "niceName":"Boots of Speed",
                     "type":0,
                     "createdAt":"2018-08-25T19:25:39.000Z",
                     "updatedAt":"2018-08-25T19:25:39.000Z",
                     "url":"http://localhost:3000/static/items/images/29.png"
                  }
               ],
               "niceName":"Phase Boots",
               "type":1,
               "createdAt":"2018-08-25T19:25:39.000Z",
               "updatedAt":"2018-08-25T19:25:39.000Z",
               "url":"http://localhost:3000/static/items/images/50.png"
            }
         ],
         "talents":[  
            "n",
            "r",
            "l",
            "r"
         ]
      }
   ]
`

**Comment by vector67** [comment]
Fixed by #227
