### ISSUE TITLE
Frontend Enhancements

### ISSUE THREAD

**Issue by steichert** [301-Redirection/DBC#216]
TODO:

- [x] Home page
- [x] Add more text to bot config to explain stuff for those users that like reading
- [x] Add path to Walkthrough page (/steamapps/common/dota 2 beta/game/dota/scripts/vscripts/)
- [x] Prevent refresh on Bot Config page
- [x] Improve alerts
- [x] Clicking Generate button on Bot Config should save bot

**Comment by SpellBreakerZA** [comment]
Some more enhancements:
- [ ] Add more text to bot config to explain stuff for those users that like reading

**Comment by SpellBreakerZA** [comment]
Fixed By #228
